# The name of the workflow
name: build

# What conditions trigger the workflow
#  In this case, pull requests on master branch
on:
  pull_request:
    branches:
      - master

# The jobs that will be run, usually in parallel
jobs:
  tests:
    name: Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout branch
        # A GitHub action for checking out the current branch
        uses: actions/checkout@master

      - name: Install node
        # A GitHub action to setup Node.js
        uses: actions/setup-node@master
        with:
          node-version: "12"

      - name: Install packages
        run: yarn install

      - name: Run Tests
        run: yarn test

      - name: Determine and publish test coverage
        # A GitHub action for running tests and publishing coverage
        uses: paambaati/codeclimate-action@v2.4.0
        env:
          # An environment variable, the value is a GitHub repo secret
          CC_TEST_REPORTER_ID: ${{ secrets.CodeClimateReporterId }}
        with:
          # Run our `coverage` script in our `package.json`
          coverageCommand: yarn coverage
          # By default, this looks for a `coverage` folder in the root of your project, but you may need to change this
          coverageLocations: "./coverage/clover.xml:clover"
          debug: true
